[project]
name = 'Decentralized-Home-Services-Provider-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.booking-management]
path = 'contracts/booking-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.customer-feedback]
path = 'contracts/customer-feedback.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
